---
- name: install redis
  apt:
    pkg: redis-server
    state: latest

- name: configure redis
  template:
    src: etc/redis/redis.conf.j2
    dest: /etc/redis/redis.conf
  notify:
    - restart redis