---
- name: install redis
  apt:
    pkg: redis-server
    state: latest

# - name: enable redis
#   service:
#     enabled: yes
#     name: redis

- name: configure redis
  template:
    src: etc/redis/redis.conf.j2
    dest: /etc/redis/redis.conf
  notify:
    - restart redis